- src/utils/createComponentWithOrderedProps.ts
- test/DateTimePicker.spec.tsx
Fixes `createComponentWithOrderedProps` to only define props that were actually provided in the original props object.
Fixes https://github.com/vaadin/hilla/issues/1545
> fix: avoid overriding component properties not specified in props

- .github/workflows/validation.yml
Try to enable validation in 2.2
> chore: enable validation on branch 2.2 (#154) (CP: 2.2)

- src/GridSortColumn.tsx
- test/Grid.spec.tsx
Fixes #130
Updated `GridSortColumn` to indicate that `headerRenderer` is not supported by this component.
- Bugfix
> fix: mark headerRenderer as unsupported for GridSortColumn

- package.json
- src/AccordionHeading.ts
- src/DetailsSummary.ts
- test/kitchen-sink/Row1.tsx
- test/kitchen-sink/Row4.tsx
Fixes #163
Added missing `AccordionHeading` and `DetailsSummary` entrypoints.
- Feature
> feat: add AccordionHeading and DetailsSummary entrypoints

- src/Select.tsx
- test/Select.spec.tsx
- test/kitchen-sink/Row8.tsx
Fixes #131
Previously, `Select` passed `props.children` to `useSimpleOrChildrenRenderer` as is. This PR changes it so that we get elements with `slot` to be rendered in light DOM, and then evaluate remaining `children` to pass to the hook.
- Bugfix
> fix: allow using slotted elements in Select

- src/utils/createComponent.ts
- test/Select.spec.tsx
- test/SideNav.spec.tsx
~Map falsy boolean properties as `undefined` to avoid them from rendering with the value `false` in the attribute, for example, `<vaadin-button hidden="false">`, which would actually evaluate as `hidden` being `true` due to it being a boolean attribute.~
Add `hidden` property to Polymer-based components to have it not set as an attribute
Fixes https://github.com/vaadin/react-components/issues/118
Bugfix
> fix: add hidden property to polymer based components

- src/utils/createComponent.ts
In Vaadin 24, the `theme` property has been removed, see https://github.com/vaadin/web-components/pull/5011.
So there is no need to exclude it anymore. Instead, we add it back with the corresponding JSDoc comment.
Updated it to remove mention of "deprecation warning" and replaced with the actual purpose.
- Documentation
> docs: update theme JSDoc to not mention deprecation

- dev/pages/Grid.tsx
- src/renderers/useRenderer.ts
- test/Grid.spec.tsx
Make the `useRenderer` hook updates synchronous to fix timing issues.
Fixes https://github.com/vaadin/react-components/issues/129
Mostly covers also https://github.com/vaadin/react-components/issues/75
Bugfix
> fix: make useRenderer hook synchronous

- package-lock.json
- package.json
- scripts/generator.ts
- src/utils/createComponent.ts
Changed to use `@lit/react` instead of `@lit-labs/react` and updated types.
In order to migrate to the new package, I had to update `createComponent` return type and copy a [few types from here](https://github.com/lit/lit/blame/25fbfba9c0f1b97d720a981831c59c08472ba6ee/packages/react/src/create-component.ts#L46-L69).
This is because of the fact that `WebComponentProps` is now replaced with `ComponentProps` type (not exported).
Some relevant changes included to the new package:
- https://github.com/lit/lit/pull/4027
- https://github.com/lit/lit/pull/4381
UPD: partially reverts #167 as `@lit/react` has [its own logic](https://github.com/lit/lit/blame/25fbfba9c0f1b97d720a981831c59c08472ba6ee/packages/react/src/create-component.ts#L59) to exclude HTMLElement API that I copied over.
- Refactor …
> refactor!: use new Lit React package instead of Lit Labs

- src/utils/createComponent.ts
As discussed internally, TypeScript seems to be doing lots of heavy calculation all the time with the `React.ComponentProps` approach…it dramatically slows down VSCode.
- Refactor
> refactor: restore original version of ComponentProps type

- src/GridColumn.tsx
- src/GridColumnGroup.tsx
- src/GridFilterColumn.tsx
- src/GridProEditColumn.tsx
- src/GridSelectionColumn.tsx
- src/GridSortColumn.tsx
- src/GridTreeColumn.ts
- test/typings/api.ts
Grid column types don't need to expose properties such as `style`, `draggable` or `onClick` from `HTMLAttributes`. This PR omits most `HTMLAttributes` props from each Grid column type.
Before:
After:
Refactor
> refactor: omit HTMLAttributes from grid column types

- src/utils/createComponent.ts
Clean up `WebComponentProps` type after https://github.com/vaadin/react-components/pull/185
Chore/refactor
> chore: clean up WebComponentProps type

- src/ChartSeries.ts
- src/ConfirmDialog.ts
- src/CookieConsent.ts
- src/Dialog.tsx
- src/LoginOverlay.ts
- src/Notification.tsx
- test/typings/api.ts
> refactor: omit HTMLAttributes from non-visual component props

- dev/pages/ContextMenu.tsx
- src/ContextMenu.tsx
- src/utils/mapItemsWithComponents.ts
- test/ContextMenu.spec.tsx
- test/typings/api.ts
Fix the support for using custom content / React components in `ContextMenu` items.
Part of https://github.com/vaadin/react-components/issues/54
Bugfix
> fix: support ReactElement as ContextMenu items

- dev/pages/MenuBar.tsx
- src/MenuBar.ts
- src/MenuBar.tsx
- test/MenuBar.spec.tsx
- test/typings/api.ts
Related to https://github.com/vaadin/react-components/pull/204
Fix the support for using custom content / React components in `MenuBar` items.
Fixes https://github.com/vaadin/react-components/issues/54
Bugfix
> fix: support ReactElement as MenuBar items

- scripts/utils/settings.ts
The issue with missing `opened-changed` event type has been fixed, so excluding it can now be removed.
- Bugfix
> fix: restore opened-changed event for MultiSelectComboBox

- src/Grid.tsx
This reverts #89 as the web component fix is now merged: https://github.com/vaadin/web-components/pull/7090
- Refactor
> refactor: revert Grid web component re-export workaround

- package.json
- scripts/generator.ts
- scripts/package-json-update.ts
Fixes #199
Related to #210
- Feature
> feat!: re-export from index.js and set sideEffects: false

- src/GridProEditColumn.tsx
This PR fixes the following error in the release build:
```
npm ERR! [dts] src/GridProEditColumn.tsx(10,33): error TS2305: Module '"./generated/Grid.js"' has no exported member 'GridColumn'.
npm ERR! [dts] src/GridProEditColumn.tsx(93,35): error TS7006: Parameter 'cell' implicitly has an 'any' type.
```
- Bugfix
> fix: import GridColumnElement from the correct file

- src/GridColumn.tsx
- src/GridColumnGroup.tsx
- src/GridFilterColumn.tsx
- src/GridProEditColumn.tsx
- src/GridSelectionColumn.tsx
- src/GridSortColumn.tsx
- src/GridTreeColumn.tsx
- test/Grid.spec.tsx
Deprecate `headerRenderer` and `footerRenderer` in favor of `header` and `footer` in Grid column types.
Closes https://github.com/vaadin/react-components/issues/146
Chore
> chore: deprecate grid column header/footer renderers

- package.json
Make sure `npm version` includes the version updates to `packages/.../package.json` in the commit.
[Here's](https://github.com/vaadin/react-components/commit/17edcfa399f45bb293549418c60551069e3d0193) an example of a version bump which only included changes to root level `package.json` and the lock file.
Bugfix
> fix: commit package updates with version

- package.json
Clean up the old lock file and `node_modules` before re-installing after version bump.
> fix: clean up before post-version install

- test/Dialog.spec.tsx
- test/MenuBar.spec.tsx
Updated some failing tests after recent changes in the web components:
- `MenuBar` tests needs to wait for the initial items to be rendered due to https://github.com/vaadin/web-components/pull/7312
- `Dialog` tests now render content in the different order, possibly a side-effect of https://github.com/vaadin/web-components/pull/7313 (not sure as it's footer / header order that changed)
- Tests
> test: fix failing tests after web components changes

- package-lock.json
- package.json
It seems that due to a recent version bump (https://github.com/vaadin/react-components/commit/4eafb874918ad912ecb08db7a12df700cd264fb3) `@types/react-dom` is not installed anymore, which breaks the build. It probably was a transitive dependency coming from some other dependency before. 
Adding it as an explicit dev dependency in order to get it installed again.
> chore: install missing dev dependency

- scripts/css-generator.ts
Related to finding from https://github.com/vaadin/web-components/issues/7976#issuecomment-2418975229
This fixes the output of CSS generator script to look like the one we had in the [original repository](https://github.com/vaadin/vaadin-lumo-styles/blob/9e3e9aa62d1922fb6f441a53866b51a7ceef791a/font-icons.html#L14).
```css
html {
--lumo-icons-align-center: '\\ea01';
--lumo-icons-align-left: '\\ea02';
--lumo-icons-align-right: '\\ea03';
/* ... */
}
```
```css
html {
--lumo-icons-align-center: '\ea01';
--lumo-icons-align-left: '\ea02';
--lumo-icons-align-right: '\ea03';
/* ... */
}
```
- Bugfix
Can be tested by running the following npm script:
```sh
npm run build:generate-css -w @vaadin/react-components
```
> fix: handle backslash in font-icons when generating CSS

- package-lock.json
- package.json
The `type-fest` was upgraded to `4.30.2` in https://github.com/vaadin/react-components/pull/279. However, this version causes TypeScript errors when running `npm run validate:types` due to https://github.com/sindresorhus/type-fest/issues/1013:
```
scripts/generator.ts:124:88 - error TS2345: Argument of type 'GenericJsContributions' is not assignable to parameter of type 'string'.
Type 'number' is not assignable to type 'string'.
```
This PR temporarily downgrades `type-fest` to `4.30.1`, which doesn't have this issue.
> chore: downgrade type-fest to 4.30.1

- package-lock.json
- package.json
The `json-schema-to-typescript` was upgraded to `15.0.3` in https://github.com/vaadin/react-components/pull/279. However, I just discovered that this version throws a JS error when generating the web types schema, which I reported in https://github.com/bcherny/json-schema-to-typescript/issues/649. To fix the schema generator in the meantime, this PR reverts the version back to `14.0.5`.
Depends on 
- https://github.com/vaadin/react-components/pull/288
> chore: revert json-schema-to-typescript to 14.0.5

- dev/kitchen-sink/Row1.tsx
- test/Popover.spec.tsx
Went through the repo to identify possible issues when using React 19. Could not find anything critical, automated tests pass and testing locally also worked fine.
The only things that needed changing were:
- One demo page passed the [`prefix` property](https://developer.mozilla.org/en-US/docs/Web/API/Element/prefix) to `AvatarGroup` which is read-only. React 19 apparently validates for that now and throws an error.
- One test required an additional delay
> chore: update test and kitchen sink to work with React 19

- packages/react-components/src/MenuBar.tsx
- test/typings/MenuBar.tsx
- test/typings/api.ts
Make `MenuBar` and `MenuBarItem` types generic so that:
- `MenuBarItem` accepts a type for custom item data, so that you can easily create custom item types
- `MenuBar` accepts a custom item type, which restricts the items that can be set, and provides that type in the `item-selected` event
Part of https://github.com/vaadin/web-components/issues/8700
Depends on https://github.com/vaadin/web-components/pull/8698
- Feature
> feat: allow adding custom data to menu bar item types

- packages/react-components/src/ContextMenu.tsx
- test/typings/ContextMenu.tsx
- test/typings/api.ts
Make `ContextMenu` and `ContextMenuItem` types generic so that:
- `ContextMenuItem` accepts a type for custom item data, so that you can easily create custom item types
- `ContextMenu` accepts a custom item type, which restricts the items that can be set, and provides that type in the `item-selected` event
Part of https://github.com/vaadin/web-components/issues/8700
Depends on https://github.com/vaadin/web-components/pull/8698
- Feature
> feat: allow adding custom data to context menu item types

- package-lock.json
- package.json
There is a following compilation warning after the 24.8.0-alpha4 bump:
```
[types]   Types of property 'part' are incompatible.
[types]     Type 'string | undefined' is not assignable to type 'DOMTokenList | undefined'.
[types]       Type 'string' is not assignable to type 'DOMTokenList'.
````
Looks like types for `part` were added in a recent PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/72230
And in `lib.dom.d.ts` there are following types:
```
get part(): DOMTokenList;
set part(value: string);
```
Let's add an explicit dev dependency to downgrade version for now.
> chore: pin @types/react to avoid TS compilation warning

- package-lock.json
- package.json
This dev dependency causes release build to fail as some agents use Node 18:
```
npm ERR! code EBADENGINE
npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: rimraf@6.0.1
npm ERR! notsup Not compatible with your version of node/npm: rimraf@6.0.1
npm ERR! notsup Required: {"node":"20 || >=22"}
npm ERR! notsup Actual:   {"npm":"10.5.0","node":"v18.20.1"}
```
Let's downgrade it for now.
> chore: downgrade rimraf to v5 to allow using Node 18

- package-lock.json
- package.json
Cherry-pick of #311 to 24.7 branch.
- Cherry-pick
> chore: downgrade rimraf to v5 to allow using Node 18 (#311) (CP: 24.7)

- packages/react-components/src/MasterDetailLayout.tsx
- test/MasterDetailLayout.spec.tsx
Make the details wrapper update its slot name every time the `children` reference changes, even if the type of component that's in `children` didn't change.
Note that the second issue mentioned in the ticket (component not detecting that a view transition needs to start) is not solved by this. This would either require Hilla change something in the file router, or a different approach for starting view transitions. I think I'll open a more specific issue for that afterwards.
Fixes https://github.com/vaadin/react-components/issues/313
- Bugfix
> fix: toggle details when nested component content changes

- packages/react-components/src/MasterDetailLayout.tsx
- test/MasterDetailLayout.spec.tsx
Make MDL verify its child components so that only `MasterDetailLayout.Master` and `MasterDetailLayout.Detail` are valid child components. Text nodes are still considered valid in order to allow for whitespace from formatting. It seems otherwise unlikely that people would try to slot text into individual areas.
Also adds JSDoc for `MasterDetailLayout` to explain how the component should be used.
Fixes https://github.com/vaadin/react-components/issues/317
- Refactor
> refactor: validate MDL child components

- dev/pages/MasterDetailLayout.tsx
Related to https://github.com/vaadin/web-components/pull/9052
The `stackThreshold` property is going to be replaced. Let's remove it from dev page to avoid possible problems when bumping web components version with a new API (we can then modify it to use the new one instead).
> chore: remove stackThreshold from MDL dev page

- package-lock.json
- package.json
Builds on main fail with TS compilation errors due to missing Node.js types: https://github.com/vaadin/react-components/actions/runs/14908506578/job/41877160875. Maybe some transitive dependency is missing due to https://github.com/vaadin/react-components/pull/321 or some change in the latest WC alpha. Let's try adding them explicitly.
- Internal
> chore: add missing node types

- dev/pages/Popover.tsx
- test/Popover.spec.tsx
- test/Select.spec.tsx
Changed to use `width` and `height`, see following PRs:
- https://github.com/vaadin/web-components/pull/9631
- https://github.com/vaadin/web-components/pull/9653
Using `null` is needed for now, as empty string isn't handled and therefore doesn't reset width / height.
This needs to be fixed in the web component, it likely also affects Dialog and ConfirmDialog.
> chore: update overlay tests and Popover dev page

- test/ComboBox.spec.tsx
- test/ContextMenu.spec.tsx
- test/Dialog.spec.tsx
- test/MenuBar.spec.tsx
- test/MultiSelectComboBox.spec.tsx
Updated tests for components to not expect overlays to be placed in the body.
Also removed the overlay close catcher since overlays are no longer teleported. 
- Test
> test: adjust components tests to overlay changes

- dev/kitchen-sink/App.tsx
Related to https://github.com/vaadin/web-components/pull/10138
Lumo is already included to the kitchen sink page since https://github.com/vaadin/react-components/pull/350
> chore: remove Lumo import from the kitchen sink
