scripts/generate.ts

Add events to generated components

---

scripts/generate.ts
src/create-component.ts
web-dev-server.config.ts

fix: Polymer element properties in the prototype

---

scripts/generator.ts
scripts/package-json-update.ts
scripts/stub-generator.ts
scripts/utils/misc.ts
scripts/utils/settings.ts
src/ChartSeries.ts
test/kitchen-sink/App.tsx

ChartSeries enables providing data for Vaadin Chart component declaratively, without relying on refs and imperative JS API.

feat: add ChartSeries component

---

package.json
scripts/package-json-version.ts

build: update dependencies' version by script

---

package.json
scripts/generator.ts
scripts/package-json-update.ts
scripts/stub-generator.ts
src/CrudEdit.ts
src/CrudEditColumn.ts

fix: add TypeScript indexable index.d.ts entrypoint

---

package.json
scripts/package-json-update.ts

Fixes https://github.com/vaadin/react-components/issues/59
Bugfix

fix: update conditional exports ordering

---

package-lock.json
package.json
scripts/package-json-update.ts

feat: extensionless entrypoints in exports

---

package-lock.json
package.json
scripts/utils/settings.ts
src/MultiSelectComboBox.tsx
src/renderers/multiSelectCombobox.d.ts
test/MultiSelectComboBox.spec.tsx
test/kitchen-sink/Row2.tsx

feat: add MultiSelectComboBox

---

package-lock.json
package.json
scripts/utils/settings.ts
src/MultiSelectComboBox.tsx
src/renderers/multiSelectCombobox.d.ts
test/MultiSelectComboBox.spec.tsx
test/kitchen-sink/Row2.tsx

Fixes #71
(cherry picked from commit 2225aa771e629b5937b1fe5f751775e1f28694f8)

feat: add MultiSelectComboBox (#90) (CP: 2.0)

---

package-lock.json
package.json
scripts/utils/settings.ts
src/MultiSelectComboBox.tsx
src/renderers/multiSelectCombobox.d.ts
test/MultiSelectComboBox.spec.tsx
test/kitchen-sink/Row2.tsx

Fixes #71
(cherry picked from commit 2225aa771e629b5937b1fe5f751775e1f28694f8)

feat: add MultiSelectComboBox (#90) (CP: main)

---

src/Grid.tsx

fix(Grid): omit re-exports from GridColumn.js

---

package-lock.json
package.json
scripts/generator.ts
scripts/stub-generator.ts
scripts/utils/misc.ts
scripts/utils/settings.ts
src/TabSheet.ts
test/kitchen-sink/App.tsx
test/kitchen-sink/Row10.tsx

Fixes #96
(cherry picked from commit f02ec33b6ff54f2dc1014cbe1c978d2524083403)

feat: add TabSheet React wrapper (#97) (CP: 2.0)

---

.github/workflows/validation.yml
scripts/cherryPick.cjs
scripts/utils/misc.ts
src/Crud.ts
test/MultiSelectComboBox.spec.tsx
test/kitchen-sink/Row3.tsx
test/kitchen-sink/data.ts

feat: add crudPath helper

---

package-lock.json
test/ComboBox.spec.tsx

Configure ComboBox in a working way

test: Fix ComboBox test (2.1)

---

.github/workflows/validation.yml

Same as #154 but for `2.3` branch.

chore: enable validation on branch 2.3

---

src/utils/createComponent.ts

Manually cherry-pick #185 to `2.3`

refactor: remove omitting of ControllerMixinClass properties (#185)

---

src/GridColumn.tsx
src/GridColumnGroup.tsx
src/GridFilterColumn.tsx
src/GridProEditColumn.tsx
src/GridSelectionColumn.tsx
src/GridSortColumn.tsx
src/GridTreeColumn.tsx
test/Grid.spec.tsx

feat: add header and footer Grid column shorthands

---

src/GridTreeColumn.ts
src/GridTreeColumn.tsx
test/Grid.spec.tsx

Manual cherry-pick of #194 to `2.3` branch.
- Cherry-pick

fix: add GridTreeColumn header and footer renderers (#194) (CP: 2.3)

---

test/Grid.spec.tsx

Improve the test coverage for synchronous grid column rendering now that each column [individually defines whether to render synchronously](https://github.com/vaadin/react-components/pull/196).
Tests

test: improve renderSync test coverage

---

test/Grid.spec.tsx

Fix flaky grid tests with wait until logic
Tests

test: fix flaky grid tests with wait until

---

package-lock.json
package.json

Updated dev dependencies to get latest Vite version.

chore: update Vite dev dependencies to latest versions

---

src/ContextMenu.tsx
src/MenuBar.tsx
src/utils/mapItemsWithComponents.ts
test/ContextMenu.spec.tsx
test/MenuBar.spec.tsx
test/typings/api.ts

fix: reference the correct item in item selected event

---

.github/workflows/validation.yml

Same as https://github.com/vaadin/react-components/pull/178 but for `24.4` branch.

chore: enable validation on branch 24.4

---

dev/pages/DashboardLayout.tsx
packages/react-components-pro/package.json
packages/react-components-pro/src/Dashboard.ts
packages/react-components-pro/src/DashboardLayout.ts
packages/react-components-pro/src/DashboardWidget.ts

Part of https://github.com/vaadin/platform/issues/6626
Fixes https://github.com/orgs/vaadin/projects/70/views/1?pane=issue&itemId=74589768
Initialized the necessary files for `Dashboard`.
- Feature

feat: create dashboard files

---

test/Grid.spec.tsx

Fix `GridPro` test cases to make them pass with [this](https://github.com/vaadin/web-components/pull/7822) web component change.
This change should be cherry-picked to `24.5` and `24.4`
Tests

test: fix grid-pro tests

---

.github/workflows/validation.yml

Same as #245 but for `24.5` branch.

chore: enable validation on branch 24.5

---

dev/pages/Dashboard.tsx
dev/pages/DashboardLayout.tsx

Enable Dashboard on dev pages
Chore

chore: enable dashboard on dev pages

---

package-lock.json
packages/react-components/package.json
packages/react-components/src/Card.ts

Added `Card` component.
- Feature

feat: add Card component

---

packages/react-components/src/utils/flushMicrotask.ts

Clean up flushMicrotask
Refactor

refactor: clean up flushMicrotask

---

.github/workflows/validation.yml

Same as #263 but for `24.5` branch.

chore: enable validation on branch 24.6

---

package-lock.json
package.json

Manual cherry-pick of #308 to `24.7` branch so we don't get that problem there after the next patch release.
- Cherry-pick

chore: pin @types/react to avoid TS compilation warning (#308) (CP: 24.7)

---

dev/pages/MasterDetailLayout.tsx
test/MasterDetailLayout.spec.tsx

Set up the MDL feature flag in the dev page and tests. Existing tests don't need it apparently, but should be good to have in any case.

chore: setup MDL feature flag

---

dev/pages/Accordion.tsx
dev/pages/AvatarGroup.tsx
dev/pages/ComboBox.tsx
dev/pages/ConfirmDialog.tsx
dev/pages/ContextMenu.tsx
dev/pages/DatePicker.tsx
dev/pages/MessageList.tsx
dev/pages/Popover.tsx
dev/pages/Select.tsx
dev/pages/TextField.tsx
dev/pages/TimePicker.tsx

Adds some more dev pages that were an outcome of testing integration of Lit component versions with React wrappers.
- Internal

chore: add more dev pages

---

.github/workflows/validation.yml

Add 24.8 to the workflow validation list.

chore: add 24.8 to validation list

---

packages/react-components-pro/src/Board.ts
packages/react-components-pro/src/BoardRow.ts

Deprecate `Board` with the intention to remove it in Vaadin 26.
Part of https://github.com/vaadin/web-components/issues/9741
- Refactor

refactor: deprecate Board
